/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.huangzl.drools6
 
import com.huangzl.drools6.HelloWorld.Message;

global java.util.List list
 
rule "admin"
    dialect "mvel"
    when
        m : Message( name == "huangzl" && result == null , name : name)
    then
        System.out.println( name + " is a admin.");
        modify ( m ) { setResult( "admin" )};
//    modify ( m ) { result = "Goodbye cruel world",
//                   status = Message.GOODBYE };
end

rule "user"
    dialect "java"
    when
        m : Message( name != "huangzl"  && result == null, name : name)
    then
        System.out.println( name + " is a user.");
        modify ( m ) { setResult( "user" )};
end
