/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package drools
 
import com.eelly.mvc.drools.Hello2.A;
import com.eelly.mvc.drools.Hello2.B;

global java.util.List list
 
rule "a"
    when
        a : A()
    then
        System.out.println("rule a ,name is :" +  a.getName());
end

rule "b"
    when
        b : B()
    then
        System.out.println("rule b ,name is :" +  b.getName());
end

rule "ab"
	when
		a : A()
		b : B()
	then
		System.out.println("rule ab ,name is :" + a.getName() + "+" + b.getName());
end

rule "aa"
	when
		a : A()
		a1 : A()
	then
		System.out.println("rule aa ,name is :" + a.getName() + "+" + a1.getName());
end

rule "aora"
	when
		//a : A() or a1 : A()
		a :( A() or A() )
	then
		System.out.println("rule aora ,name is :" + a.getName() + "," + a);
end

rule "null when"
	when
		
	then
		System.out.println("rule null when ");
end
